openy/urls.py
from django.urls import path
from . import views

app_name = "openy"

urlpatterns = [
    path("", views.home, name="home"),
    path("settings", views.settings, name="settings"),
    path("upload", views.upload, name="upload"),
    path("draw", views.draw, name="draw"),
    path("explore", views.explore, name="explore_root"),
    path("explore/<slug>", views.explore, name="explore"),
    path("node/<uid>", views.explore_node, name="explore_node"),
    path("find_entry", views.find_entry, name="find_entry"),
    path("train", views.train, name="train"),
    path("train-position", views.train_position, name="train_position"),
    path("board", views.board, name="board"),
    path("exercise/<eid>", views.exercise, name="exercise"),
    path("exercise/<eid>/delete", views.exercise_delete, name="exercise_delete"),
    path("exercise/<eid>/failure", views.exercise_failure, name="exercise_failure"),
    path("exercise/<eid>/success", views.exercise_success, name="exercise_success"),
    path("graph", views.graph, name="graph"),
    path("summary", views.summary, name="summary"),
    path("notes", views.notes, name="notes"),
    path("utils.js", views.js_utils, name="js_utils"),
]

openy/templates/openy/base.html
{% load static %}

<!DOCTYPE html>

<html>

<head>
    <title>{% block title %}Openy{% endblock %}</title>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <link rel="icon" href="{% static 'openy/icon.png' %}" />
    {% block stylesheets %}
    <link rel="stylesheet" href="{% static 'openy/css/base.css' %}" />
    {% endblock stylesheets %}
</head>

<body>
    <script type="text/javascript" src="{% url 'openy:js_utils'%}" ></script>
    {% block body %}{% endblock body %}
</body>

</html>

openy/templates/openy/board.html
{% extends 'openy/base.html' %}
{% load static %}

{% block stylesheets %}
{{ block.super }}
<style media="screen">
    .wrapper {
        display: flex;
        flex-direction: column;
        padding: 8px;
    }

    .wrapper>* {
        margin: 0 auto 8px auto;
        width: 600px;
        max-width: 100%;
    }

    .wrapper>*:last-child {
        margin-bottom: 0;
    }

    #fen_form {
        display: flex;
        flex-direction: row;
        justify-content: center;
    }

    #fen_form>* {
        padding: 8px;
        font-family: inherit;
        font-size: 12px;
        border: none;
        color: white;
    }

    #input_fen {
        border-top-left-radius: 4px;
        border-bottom-left-radius: 4px;
        background: #2F2F2F;
        width: 100%;
    }

    #input_fen_button {
        border-top-right-radius: 4px;
        border-bottom-right-radius: 4px;
        cursor: pointer;
        width: 64px;
        background: #2F2F2F;
        flex-shrink: 0;
    }

    #input_fen_button:hover {
        background: #383838;
    }

    .line {
        font-size: 12px;
    }
</style>
<link rel="stylesheet" href="{% static 'openy/css/board.css' %}" />
<link rel="stylesheet" href="{% static 'openy/css/line.css' %}" />
{% endblock stylesheets %}

{% block title %}Board • {{block.super}}{% endblock %}

{% block body %}
<div class="wrapper">
    <div id="fen_form">
        <input id="input_fen" type="text" name="name" placeholder="Enter a valid FEN string" />
        <button id="input_fen_button" type="button" name="button">Set FEN</button>
    </div>
    <div id="board" class="board"></div>
    <div class="line"></div>
</div>

<script type="text/javascript" src="{% static 'openy/js/board.js' %}"></script>
<script type="text/javascript" src="{% static 'openy/js/explore.js' %}"></script>
<script type="text/javascript">
    let boardStatus = initBoard(document.querySelector(".board"), STARTING_FEN, (fen, move) => {
        document.querySelector(".line").innerHTML = boardStatus.history.line();
    });
    document.getElementById("input_fen_button").addEventListener("click", (event) => {
        let fen = document.getElementById("input_fen").value.trim();
        boardStatus.pushFen(fen);
        document.getElementById("input_fen").value = "";
    });
</script>
{% endblock %}

openy/templates/openy/exercise.html
{% extends 'openy/layout.html' %}
{% load static %}

{% block title %}Exercise • {{block.super}}{% endblock title %}

{% block stylesheets %}
{{block.super}}
<link rel="stylesheet" href="{% static 'openy/css/board.css' %}" />
<link rel="stylesheet" href="{% static 'openy/css/exercise.css' %}" />
<link rel="stylesheet" href="{% static 'openy/css/line.css' %}" />
{% endblock stylesheets %}

{% block section %}

<h1>{{exercise.title}}</h1>

{% if exercise.description %}
<p>{{exercise.description}}</p>
{% endif %}

<div class="exercise">
    <div class="exercise__board">
        <div class="board"></div>
        <div class="exercise__start_button">Start</div>
        <div id="exercise_popup__success" class="exercise_popup">
            <img class="exercise_popup__icon" src="{% static 'openy/svg/checkmark.svg' %}" alt="">
            <div class="exercise_popup__title">Success</div>
            <div class="exercise_popup__button">OK</div>
        </div>
        <div id="exercise_popup__failure" class="exercise_popup">
            <img class="exercise_popup__icon" src="{% static 'openy/svg/close.svg' %}" alt="">
            <div class="exercise_popup__title">Failure</div>
            <div class="exercise_popup__button">OK</div>
        </div>
    </div>
    <div class="exercise__sidebar">
        <div class="exercise__sidebar__clock">
            <img class="icon" src="{% static 'openy/svg/clock.svg' %}" alt=""><span class="exercise__sidebar__timer">00:00</span>
        </div>
        <div class="exercise__sidebar__line line line--vertical"></div>
        <div class="exercise__sidebar__buttons">
            <div class="exercise__sidebar__buttons__restart"><img title="Restart" class="icon" src="{% static 'openy/svg/reload.svg' %}" alt="Restart"></div>
            <!--<div class="exercise__sidebar__buttons__explore"><img title="Explore" class="icon" src="{% static 'openy/svg/search.svg' %}" alt="Explore"></div>-->
            <div class="exercise__sidebar__buttons__copy"><img title="Clip FEN" class="icon" src="{% static 'openy/svg/clipboard.svg' %}" alt="Copy"></div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static 'openy/js/board.js' %}"></script>
<script type="text/javascript" src="{% static 'openy/js/exercise.js' %}"></script>
<script type="text/javascript">
    let boardStatus = initBoard(document.querySelector(".board"), null, null);
    let exercise = initExercise(document.querySelector(".exercise"), boardStatus, "{{exercise.starting_position}}", "{{exercise.moves}}", {% if exercise.first_move %}true{% else %}false{% endif %});
</script>
<script type="text/javascript" src="{% static 'openy/js/explore.js' %}"></script>


{% endblock %}

openy/templates/openy/explore.html
{% extends 'openy/layout.html' %}
{% load static %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'openy/css/board.css' %}" />
<link rel="stylesheet" href="{% static 'openy/css/evaluation.css' %}" />
<link rel="stylesheet" href="{% static 'openy/css/repertoire.css' %}" />
<link rel="stylesheet" href="{% static 'openy/css/explore.css' %}" />
<link rel="stylesheet" href="{% static 'openy/css/line.css' %}" />
{% endblock stylesheets %}

{% block title %}Exploring {{node.line}} • {{ block.super }}{% endblock title %}

{% block section %}
    <h1>Exploring the Database</h1>
    <p class="line_wrapper">
        <span class="line line--noflex">{{node.line}}</span>
        <img class="line_external" id="train_shortcut" href="{% url 'openy:train_position' %}" csrf="{{csrf_token}}" title="Train this position" src="{% static 'openy/svg/external.svg' %}" alt="Train" />
    </p>
    <div class="explore_table">
        <div class="board_bar">
            <div id="bar1" class="evaluation_bar"></div>
            <div id="board1" class="board"></div>
        </div>
        <div class="history">
            {% if node.parent %}
            <table>
                {% for ancestor in node.ancestors %}
                <tr>
                    <td class="history_anchor" history_anchor="{{ forloop.counter0 }}">{{ancestor.short_label}}</td>
                    <td style="color: {{ancestor.color}}">{{ancestor.evaluation}}</td>
                    <td>{% if ancestor.comment %}{{ancestor.comment | capfirst}}{% else %}&ndash;{% endif %}</td>
                </tr>
                {% endfor %}
            </table>
            {% endif %}
        </div>
    </div>

    <div id="repertoire1" class="repertoire" style="height: 420px" target="{{node.uid}}">
        <a id="repertoire_center_button" title="Center on current node" class="repertoire__fullscreen_link"><img src="{% static 'openy/svg/home.svg' %}" alt="Home"></a>
        <a title="Draw full repertoire" class="repertoire__fullscreen_link" href="{% url 'openy:graph' %}"><img src="{% static 'openy/svg/fullscreen.svg' %}" alt="Fullscreen"></a>
    </div>

    <script type="text/javascript">
        var csrfToken = "{{ csrf_token }}";
        var findEntryUrl = "{% url 'openy:find_entry' %}";
    </script>
    <script type="text/javascript" src="{% static 'openy/js/board.js' %}"></script>
    <script type="text/javascript" src="{% static 'openy/js/repertoire.js' %}"></script>
    <script type="text/javascript" src="{% static 'openy/js/evaluation.js' %}"></script>
    <script type="text/javascript" src="{% static 'openy/js/explore.js' %}"></script>
    <script type="text/javascript">
        let boardStatus = initBoard(document.querySelector("#board1"), STARTING_FEN, createBoardCallback("{{node.uid}}"));
        {% if node.label %}
        {% for ancestor in node.ancestors reversed %}
        boardStatus.pushUciMove("{{ancestor.move_uci}}");
        {% endfor %}
        {% endif %}
        initRepertoire(document.querySelector("#repertoire1"), "{% url 'openy:draw' %}?center={{node.uid}}&pred=2&succ=2");
        initEvaluationBar(document.querySelector("#bar1"), "{{node.evaluation}}");
        setTrainShortcut(document.getElementById("train_shortcut"), boardStatus);
        let historyLength = document.querySelectorAll(".history_anchor").length;
        document.querySelectorAll(".history_anchor").forEach((item, i) => {
            item.addEventListener("click", (event) => {
                boardStatus.goToHistory(historyLength - parseInt(event.target.getAttribute("history_anchor")));
            });
        });
    </script>
{% endblock %}

openy/templates/openy/graph.html
{% extends 'openy/base.html' %}
{% load static %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'openy/css/repertoire.css' %}">
<style media="screen">
    html {
        position: fixed;
        overflow: hidden;
        width: 100vw;
        height: 100vh;
    }
    body {
        margin: 0;
        padding: 0;
    }
    .repertoire {
        width: 100%;
        height: 100%;
    }
    .repertoire svg {
        background: none;
    }
</style>
{% endblock stylesheets %}

{% block title %}Board • {{block.super}}{% endblock %}

{% block body %}
<div id="repertoire1" class="repertoire">
</div>
<script type="text/javascript" src="{% static 'openy/js/repertoire.js' %}"></script>
<script type="text/javascript">
    let rep = initRepertoire(document.querySelector("#repertoire1"), "{% url 'openy:draw' %}");
</script>
{% endblock %}

openy/templates/openy/home.html
{% extends 'openy/layout.html' %}
{% load static %}

{% block section %}
<h1>Openy</h1>

<p>
    <b>Openy</b> is a <a href="//www.djangoproject.com/">Django</a> application to learn chess openings.
    It takes textual notes as input, and provides tools to explore and memorize them.
    View it on <a href="//github.com/ychalier/openy/">GitHub</a>.
</p>

<h2>Database initialization</h2>

<p>First, write notes in a text file, with the following format:</p>

<pre>
    1. e4 : Takes the center
       1. ... e5 : Again, black takes the center
           2. Nf3
               2. ... Nc6
                   3. d4 : Scotch opening
       1. ... c5 : Sicilian defence
</pre>

<p>
Note that indentation is ignored by the parser, as well as blank lines or any
line not following that format (i.e. one move per line, in
<a href="https://en.wikipedia.org/wiki/Algebraic_notation_(chess)">standard
algebraic notation</a>, possibly followed by a textual comment ;
respect punctuation and spaces in the example for lines to be correctly parsed).
</p>
<p>
Second, use the parsing script <code>scripts/parser.py</code>. It requires a
UCI chess engine executable, such as <a href="https://stockfishchess.org/">Stockfish</a> or
<a href="https://komodochess.com/">Komodo</a>. It will
output a JSON file (called by default <code>repertoire.json</code>).
</p>
<p>
Finally, upload this JSON file to the website through the form in
<a href="{% url 'openy:settings' %}">Openy's settings</a>.
This will populate the database with your notes.
</p>

<h2>Built With</h2>

<ul>
    <li>Some SVG icons are imported from the <a href="https://github.com/danklammer/bytesize-icons">Bytesize Icons</a> library.</li>
    <li>Theme and piece graphics are from the <a href="https://www.chess.com/">Chess.com</a> website.</li>
    <li>Python's chess mechanics are implemented by the <a href="https://python-chess.readthedocs.io/en/latest/">python-chess</a> module.</li>
</ul>

<hr>

<blockquote>
    La partie d'Échecs dépend de trois facteurs : la <b>matière</b> (représentée
    par les 32 pièces), l'<b>espace</b> (représenté par les 64 cases de l'échiquier),
    et le <b>temps</b> (représenté par les coups). En décomposant ce dernier, le temps,
    on peut distinguer d'une façon générale, trois phases principales qui ne
    sont pas strictement limitées : le <b>début</b>, où les deux adversaires cherchent
    à développer leur pièces ; le <b>milieu</b>, où le combat des armées bat son plein ;
    la <b>fin</b>, où la réduction du matériel diminue le danger du mat, mais exige une
    précision d'autant plus grande dans tous les mouvements, car les erreurs y
    sont, malgré la simplicité apparente de la position, très faciles à
    commettre et très difficiles à réparer.
</blockquote >

<p style="text-align:center">
    <cite>Bréviaire des échecs</cite> by Xavier Tartakover, 1933.
    <br>
    <br>
    <img src="{% static 'openy/icon.png' %}" alt="" />
</p>

{% endblock %}

openy/templates/openy/layout.html
{% extends 'openy/base.html' %}
{% load static %}


{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'openy/css/layout.css' %}" />
{% endblock stylesheets %}

{% block body %}
<div class="body_wrapper">
    <div class="fullheight_padding"></div>
    <header class="header header--inline">
        <nav class="header__nav navbar">
            <a href="{% url 'openy:home' %}" class="header__title">Openy</a>
            {% if request.user.is_authenticated %}
                <span class="hide_on_small">&middot;</span>
                <a href="{% url 'openy:explore_root' %}">Explore</a>
                <a href="{% url 'openy:train' %}">Train</a>
                <a href="{% url 'openy:board' %}">Board</a>
                {% if request.user.is_staff %}
                    <span class="hide_on_small">&middot;</span>
                    <a href="{% url 'openy:settings' %}">Settings</a>
                {% endif %}
            {% endif %}
        </nav>
    </header>
    <section>
        {% block section %}{% endblock section %}
    </section>
    <div class="fullheight_padding"></div>
</div>
{% endblock body %}

openy/templates/openy/settings.html
{% extends 'openy/layout.html' %}
{% load static %}

{% block title %}Settings • {{block.super}}{% endblock title %}

{% block stylesheets %}
{{block.super}}
<link rel="stylesheet" href="{% static 'openy/css/forms.css' %}" />
{% endblock %}

{% block section %}
<h1>Settings</h1>


<div>
    <p>
        Upload a JSON repertoire
    </p>
    <form class="form--inline" method="post" action="{% url 'openy:upload' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <label class="button button--text" for="inputFile">Browse...</label>
        <div class="input--file">
            <input id="inputFile" type="file" name="file" accept=".json" />
        </div>
        <span id="inputFileFilename" style="line-height: 37px"></span>
        <input class="button button--contained" type="submit" value="Upload"/>
    </form>
    <p>
        Check the <a href="{% url 'openy:home' %}">homepage</a> for detailed
        instructions on how to get this file.
    </p>
</div>

<br>

<form class="form--full" action="" method="post">
    {% csrf_token %}
    <div class="input input--outlined">
        <label for="inputFailureCoef">Failure Ratio Coefficient</label>
        <input id="inputFailureCoef" type="number" step="0.01" name="failure_coef" value="{{profile.failure_coef}}" />
    </div>
    <div class="input input--outlined">
        <label for="inputInactivityCoef">Inactivity Ratio Coefficient</label>
        <input id="inputInactivityCoef" type="number" step="0.01" name="inactivity_coef" value="{{profile.inactivity_coef}}" />
    </div>
    <div class="input input--outlined">
        <label for="inputEaseCoef">Ease Ratio Coefficient</label>
        <input id="inputEaseCoef" type="number" step="0.01" name="ease_coef" value="{{profile.ease_coef}}" />
    </div>
    <div class="input input--outlined">
        <label for="inputEloVolatility">ELO Volatility</label>
        <input id="inputEloVolatility" type="number" step="0.01" name="elo_volatility" value="{{profile.elo_volatility}}" />
    </div>
    <div class="input input--outlined">
        <label for="inputEloSpreading">ELO Spreading</label>
        <input id="inputEloSpreading" type="number" step="0.01" name="elo_spreading" value="{{profile.elo_spreading}}" />
    </div>
    <input class="button button--contained" type="submit" value="Save" />
</form>

<script type="text/javascript">
    document.getElementById("inputFile").addEventListener("change", (event) => {
        document.getElementById("inputFileFilename").textContent = event.target.value.split("\\").pop();
    });
</script>

{% endblock %}

openy/templates/openy/summary.html
{% extends 'openy/layout.html' %}
{% load static %}

{% block title %}Summary • {{block.super}}{% endblock title %}

{% block stylesheets %}
{{ block.super }}
<style media="screen">
    table {
        width: 100%;
    }
    td {
        text-align: center;
    }
    th {
        word-break: break-all;
    }
    td a, th a {
        color: white;
        text-decoration: none;
    }
</style>
{% endblock %}

{% block section %}

<h1>Summary</h1>

<p>Click on a column's name use it as a sorting key.</p>

<table>
    <tr>
        <th><a href="?order_by=exercise_id&desc=0">Exercise</a></th>
        <th><a href="?order_by=elo">ELO</a></th>
        <th><a href="?order_by=tries">Tries</a></th>
        <th><a href="?order_by=successes">Won</a></th>
        <th><a href="?order_by=failures">Lost</a></th>
        <th><a href="?order_by=failure_ratio">Failure<br>Ratio</a></th>
        <th><a href="?order_by=inactivity_ratio">Inactivity<br>Ratio</a></th>
        <th><a href="?order_by=ease_ratio">Ease<br>Ratio</a></th>
        <th><a href="?order_by=computed_weight">Training<br>Weight</a></th>
    </tr>
{% for pos in positions %}
<tr>
    <td><a href="{% url 'openy:exercise' eid=pos.exercise.id %}">{{pos.exercise.id}}. {{pos.exercise.title}}</a></td>
    <td>{{pos.elo|floatformat:0}}</td>
    <td>{{pos.tries}}</td>
    <td>{{pos.successes}}</td>
    <td>{{pos.failures}}</td>
    <td>{{pos.get_failure_ratio|floatformat:2}}</td>
    <td>{{pos.get_inactivity_ratio|floatformat:2}}</td>
    <td>{{pos.get_ease_ratio|floatformat:2}}</td>
    <td>{{pos.computed_weight|floatformat:2}}</td>
</tr>

{% endfor %}

</table>

{% endblock %}

openy/templates/openy/train.html
{% extends 'openy/layout.html' %}
{% load static %}

{% block title %}Train • {{block.super}}{% endblock title %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'openy/css/board.css' %}" />
<link rel="stylesheet" href="{% static 'openy/css/forms.css' %}" />
<link rel="stylesheet" href="{% static 'openy/css/train.css' %}" />
{% endblock stylesheets %}

{% block section %}
<h1>Train Openings</h1>

<form class="training_progress" action="" method="POST">
    {% csrf_token %}

    <div class="training_progress__stat">
        <div class="training_progress__stat__figure">{{elo|floatformat:"0"}}<div class="training_progress__stat__label">ELO</div></div>
    </div>
    <div class="training_progress__stat">
        <div class="training_progress__stat__figure">{{total_tries}}<div class="training_progress__stat__label">completed</div></div>
    </div>

    <div class="training_progress__stat">
        <div class="training_progress__stat__figure">{% if success_ratio %}{{success_ratio}}%{% else %}&mdash;{% endif %}<div class="training_progress__stat__label">success</div></div>
    </div>
    <div class="training_progress__stat">
        <div class="training_progress__stat__figure">{% if success_coverage %}{{success_coverage}}%{% else %}&mdash;{% endif %}<div class="training_progress__stat__label">coverage</div></div>
    </div>
    <div class="training_progress__button training_progress__button--large">
        <input class="button button--contained" type="submit" name="start_training" value="Train">
    </div>
</form>

{% if recent_trainings %}
<h3>Recent Trainings</h3>
<div class="exercise_list">
    {% for training in recent_trainings %}
    <div class="exercise_thumbnail">
        <a href="{% url 'openy:exercise' eid=training.exercise.id %}">
            <div class="board" disabled fen="{{training.exercise.cover_position}}"></div>
            <span class="exercise_thumbnail__title">{{training.exercise.title}}</span>
        </a>
    </div>
    {% endfor %}
</div>
{% endif %}

<h2>Custom Exercises</h2>

{% if custom_exercises %}
<div class="exercise_list">
    {% for exercise in custom_exercises %}
    <div class="exercise_thumbnail">
        <a href="{% url 'openy:exercise' eid=exercise.id %}">
            <div class="board" disabled fen="{{exercise.cover_position}}"></div>
            <span class="exercise_thumbnail__title">{{exercise.title}}</span>
        </a>
        <a class="exercise_thumbnail__delete" href="{% url 'openy:exercise_delete' eid=exercise.id %}">&times;</a>
    </div>
    {% endfor %}
</div>

<br>
{% endif %}

<form class="form_train" action="" method="POST">
    <div>
        <p>
            Perform the sequence of moves to memorize on the board to the right:
        </p>
        <input id="inputLine" type="text" name="line" placeholder="Move sequence in standard algebraic notation" />
        <div class="input input--toggle">
            <input id="turn" type="checkbox" name="turn" />
            <span>Play as White</span>
            <label for="turn">
                <div class="input--toggle__ball"></div>
            </label>
            <span>Black</span>
        </div>
        {% csrf_token %}
        <p>
            <input class="button button--contained" type="submit" name="start_custom" value="Create">
        </p>
    </div>
    <div id="formBoard" class="board"></div>
</form>

<p>
    Monitor exercises with the training <a title="Summary" href="{% url 'openy:summary' %}">Summary</a> panel.
</p>

<script type="text/javascript" src="{% static 'openy/js/board.js' %}"></script>
<script type="text/javascript">
    let boardStatus = initBoard(document.querySelector("#formBoard"), STARTING_FEN, (fen) => {
        document.getElementById("inputLine").value = boardStatus.history.line();
    });
    document.querySelectorAll(".exercise_list .board").forEach((item, i) => {
        initBoard(item, item.getAttribute("fen"), null);
    });
</script>

{% endblock %}